### ISSUE TITLE
Nanopolish version doesn't exist on MacOS

### ISSUE THREAD

**Issue by jameshadfield** [artic-network/artic-ncov2019#22] opened 2020-04-02 01:53 UTC
We currently require `nanopolish=0.12.5` but on MacOS the most recently available version is [0.11.3](https://anaconda.org/bioconda/nanopolish).

Unsure what the best solution is:
* Mandate the the repo is linux only
* Allow 0.11.3 (`nanopolish=0.11.3|0.12.5`)
* Update the available MacOS version to 0.12.5 (in which case i'll make an issue there)

**Comment by will-rowe** [comment] 2020-04-03 11:19
I was running into this whilst testing the fieldbioinformatics pipeline on OSX

The pipeline requires nanopolish features that aren't available in 0.11.3 - so your first option is the best solution currently.

I had been ignoring this and just installing nanopolish from source whilst testing, but we are going to need a fix. Any idea what the issue is with getting the latest nanopolish for mac into conda? I'm guessing there is one! I can have a stab at it next week maybe

**Comment by nickloman** [comment] 2020-04-03 12:41
@jts looked at this a bit, not sure how far he got?

**Comment by jts** [comment] 2020-04-03 12:45
Not very far unfortunately - the conda maintainers changed the nanopolish build script for 0.12.0 so this will take a bit of work. I can help but won't have a ton of time today

**Comment by jts** [comment] 2020-04-03 14:26
Does anyone know what version of MacOS conda builds against? I'm on 10.15.3 and hitting this header error with the conda version of gcc (4.8):

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90835

**Comment by nickloman** [comment] 2020-04-03 14:34
Is it 10.9?

**Comment by jts** [comment] 2020-04-03 14:58
for those that want to see me struggle, I'm trying to fix this here: https://github.com/bioconda/bioconda-recipes/pull/21282

**Comment by jmarshall** [comment] 2020-04-06 12:14
This will be fixed by bioconda/bioconda-recipes#21330.

**Comment by jts** [comment] 2020-04-06 12:59
This is great @jmarshall, thanks so much for fixing this.

**Comment by will-rowe** [comment] 2020-04-06 14:04
Thanks @jmarshall - that's brilliant! And thank you too @jts

**Comment by nickloman** [comment] 2020-04-15 12:09
I believe this is now fixed.

**Closed as completed by nickloman** 2020-04-15 12:09 UTC
